### ISSUE TITLE
ConvertESubGraph: Getting error while executing driver code

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#100]
@cckuhlman @Lucaslhm

For snap method **ConvertESubGraph**, we are unable to execute driver code.
Please refer to the attachment which contains all the required input.
[ConvertESubGraph.zip](https://github.com/NSSAC/CINES/files/4711978/ConvertESubGraph.zip)

The folder **constructing driver**: have all the driver constructing file and driver code .py file.
The folder **parsing**: have all the inputs required to parse the snap method.
The third folder **ConvertESubGraph** is to execute the driver code.

Thanks,
Anju

**Comment by cckuhlman** [comment]
@anju-thute 

I think we are going to need a new zip file for this.

The issue name is ConvertESubGraph.

But the supplied snap input file is:  GetESubGraph
Also, the IRs are for:  GetESubGraph
The driver code main() method is for:  ConvertESubGraph

So we are mixing together here two differen snap methods here.

chris

**Comment by anju-thute** [comment]
Hi Chris,

Sorry for the mismatch in attaching the file. Now I have updated the .zip folder by replacing the existing one with new contains input.

Thanks,
Anju

**Comment by cckuhlman** [comment]
@anju-thute 

This still has two snap methods mixed together.

Snap input file is: ConvertESubGraph
The IRs are for: ConvertESubGraph
The driver code main() method is for: GetESubGraph

chris

**Comment by anju-thute** [comment]
Sorry for the inconsistency. Please refer to the updated folder.
[ConvertESubGraph.zip](https://github.com/NSSAC/CINES/files/4717693/ConvertESubGraph.zip)

**Comment by cckuhlman** [comment]
[all.files.issue.100.snap.ConvertESubGraph.tar.gz](https://github.com/NSSAC/CINES/files/4732826/all.files.issue.100.snap.ConvertESubGraph.tar.gz)

The python driver main method and all verification cases are in the tarball.

See the comment that I made in issue #99 for a similar snap method.  That problem description is applicable here.  And so is the new datatype called for there.  It should be useable here.  The python main() driver method is correct.  It runs.  So, if you use the IRs and the new template, as described in issue #99 here, then you should be able to reproduce the driver code in the attached tarball.

Note that for this snap method, the input graph must be of type PNEANet.  Same for code in issue #99.  

Now, there is a second problem here.  This method has an argument called RenumberNodes.  This is a bool.  If  False, then the subgraph that is produced has the same node numbering as the original graph.  If True, then the resulting subgraph on n nodes has node IDs from 0 to (n-1).
The problem is that the variable always evaluates True.  I do not know why.  It appears to be an argparse problem.

See if you get the same error.

So, the test cases are like this (test cases are in tarball).  The RenumberNodes=False for the first two test cases, so the nodes should not be renumbered.  So the *.valid output files will not agree with the results that I produce, because, again the variable changes to True, so node IDs get renumbered.  The *.valid output file contents are correct:  they use the original node IDs (which corresponds to RenumberNodes=False).  When you run ./run.diff, you will see the differences.

The last two test cases have RenumberNodes=True, so the node IDs should be renumbered, and when you ./run.all, then ./run.diff, the last two test cases should give correct output.

chris

**Comment by anju-thute** [comment]
Thanks, Chris!

We copied the provided .tar folder locally and tried to execute the driver, hence it is working correctly.
So we have committed the changes into the GitHub.

Thanks,
Anju
