### ISSUE TITLE
Sort is returning incorrect results

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#141]
On job listing page, when the user first lands, he/she sees the job list of their own. However if the user sorts on any of the column - e.g. created date, the results contain jobs run by other users. The metadata does not show any information.

E.g. the logged in user has 5 jobs run.
On applying sort, the jobs of other users are also listed

**Comment by dmachi** [comment]
There are actually two bugs here.  One on the client and one on the server.  The reason these fail is because the client is sending an invalid query.  The parenthesis don’t match up in the queries with sort() in this case.  Sometimes it is &sort(-creation_date) and sometimes it is &sort(+creation_date)). The latter has two parentheses.  So that is causing a failure.  However, it should fail with an error, but for some reason the parsing library I am using is not erring and is just parsing it incorrectly.  I will work on the latter, but the former needs to be fixed in the UI code.

**Comment by dmachi** [comment]
There is still a bug in the underlying library. I've filed a ticket on that project, we'll see if they respond.  In the mean time, I've made some adjustments to ensure that even in the event of an invalid query, the appended portion (the user id) will still be applied.  It appears to be working to me.  Please test.

**Comment by murli1201** [comment]
Fixed and working fine now.
