### ISSUE TITLE
Getting error while submitting jobs with updated rules for CSonNet Simulation form.

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#163]
@cckuhlman 

Hi Chris, 
I tried updating the file model_definition.json in our CINES project from https://github.com/NSSAC/cines-csonnet-json/blob/main/final/model_definition.json. But the job submission throws an error for SEIR and SIR models. After digging out for sometime, I found that in the commit https://github.com/NSSAC/cines-csonnet-json/commit/769c2d4f63dc78e776ed5b01d5131876e773a530#diff-f695a41d2bbd806dd92a6ec56244191508a1e8a9f0b8871a90f7d772865bf0c2 , changing the properties 'discrete_time_auto' to 'discrete' and 'node_probability_auto' to 'node_probability' are causing the error.

For the time being, I have reverted the changes back so that the jobs are submitted without any error.

Thank you.

**Comment by cckuhlman** [comment]
@dmachi 

Dustin:  I will please ask you to give your view.  First, I will describe the situation.

Hey Murli:  Sorry for problem.

Higher level questions.  When you submit the jobs, are they running without error?  Or, are you testing whether the job was submitted?

The two changes that you cite were made by me because when I tested the back-end simulation code that runs the simulation several days ago, the property values "discrete_time_auto" and "node_probability_auto" will cause the back-end simulation code to die (i.e., not run).  For example, *none* of SIR-fixed, SEIR-fixed-fixed, SEIR-fixed-stochastic, and SEIR-stochastic-fixed will run with property discrete_time_auto.  The back-end simulation code wants that property value to be "discrete".  When the property is "discrete" rather than "discrete_time_auto", all of these codes run successfully.

The same can be said for value "node_probability".  If the value is "node_probability" then the back-end code runs on SEIR-fixed-stochastic, SEIR-stochastic-fixed, and SEIR-stochastic-stochastic.  If the value is "node_probability_auto", then none of these jobs runs.

I just now reran these jobs 5 test cases, and I have the same findings as I obtained previously.

So, this is why I ask the questions:
Are you testing only the web app and the process of submitting a job?
Are your jobs, when you submit them with the values you desire, running to completion? (This will be highly surprising, if true, because that would suggest that the back-end code that I am testing is not what is in net.science.)
If you do not care whether the jobs run to completion, and are only testing the web app, then perhaps what you are doing right now is fine.

@dmachi :  with the changeout of the back-end code coming, if Persistent is only testing the web app right now, then perhaps it is best just to have Murli continue testing with his changes---his changes back to "node_probability_auto" and "discrete_time_auto."  Or perhaps you want Murli to answer first.

chris

**Comment by murli1201** [comment]
@cckuhlman @dmachi 

When you submit the jobs, are they running without error? Or, are you testing whether the job was submitted?
- When I use properties 'discrete_time_auto' and 'node_probability_auto', the jobs get submitted without any error and are also completed.
- When I use properties 'discrete' and 'node_probability', the job submission throws error.

Are you testing only the web app and the process of submitting a job?
-  Yes, right.

Are your jobs, when you submit them with the values you desire, running to completion?
-  Yes, true.

**Comment by dmachi** [comment]
Murli’s jobs had been running successfully for a little while.  Currently your updates to model.json without a corresponding update to the csonnet image that is in SciDuct is causing the current failure.  This is simply because the image is what contains the schema that validates input (which has changed with the updated model.json).  

I will also be updating model.json to reflect the updates to fixed vs network vs decorated network…hopefully today.  @murli1201 I think you should just stick with the old model.json until we update both the image and model.json.  I will let you know when that happens.

**Comment by murli1201** [comment]
Okay, Dustin.

Thank you.
