### ISSUE TITLE
Admin privs in webapp

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#206]
To the permissions verifications for files, can you please add a check for "superadmin" in the users roles in the same places that were just done for the public check.  Technically the user already has administrative permissions, but the UI is just not allowing it to be used.  This will greatly help me help others.    The same should apply to the "write" too, but i'm less concerned about that for now.

**Comment by murli1201** [comment]
Hi Dustin, 

Currently, we are checking for 'teams' and not checking for 'roles' for read/write rights because we get roles as am empty array from the token data.

Data recieved from token is as shown below-
accounts: ["ARCS:bii_nssac"]
application: "net.science_dev"
aud: (4) ["fileservice", "jobservice", "userservice", "net.science_dev"]
exp: 1624028168
first_name: "Manvitha"
iat: 1623941768
iss: "https://sciduct.bii.virginia.edu/usersvc/public_key"
last_name: "Akula"
max_reval_time: 300
nbf: 1623941768
roles: []
scope: "user"
sub: "Manvitha"
teams: ["epihiper"]


But I have made changes to file 'src\app\auth\authRoles.js'. I think this might help. I have also attached the screenshot of the changes I have made.
![Screenshot (88)](https://user-images.githubusercontent.com/54397265/122510921-0cf95900-d024-11eb-9890-fa4bb621f60e.png)

I will comment once I merge these changes to master so that you can verify.

Thank you.

**Comment by dmachi** [comment]
Right, roles are orthogonal to the teams.  They are less common, but my account is one of those :)

Its not clear to me that we are really using that authRoles component in the infrastructure….we don’t have admin, staff, or user groups.  I can try it out in the morning.   I would think anywhere that you check for team membership, you would simply also check to see if the user’s role from their token has “superadmin”.

**Comment by murli1201** [comment]
I have made checks for read as well as write permissions for 'superadmin'. I have made an assumption that roles in your account looks like roles=['superadmin']. I hope this works. Please verify and revert in case it doesnt work.

I have also merged the changes to the master.

**Comment by dmachi** [comment]
Fixed.
