### ISSUE TITLE
plot code to generate a graph is failing (this is the visualization

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/CINES#342]
Trying to plot (visualize) an 8-node graph.  Job inputs on form appear to be fine.  Submit button works and job is submitted.  But it fails.

There seems to be something amiss with the argument list, for the software invocation on the back end.

I cannot tell whether the color argument has no value, or too many, or what.

The job and the error message (from std err) are attached.
<img width="1403" alt="Screen Shot 2023-05-03 at 11 41 25 AM" src="https://user-images.githubusercontent.com/45767588/235967695-84295da6-3a43-49fe-91a1-dd2639c3d937.png">
<img width="686" alt="Screen Shot 2023-05-03 at 11 40 56 AM" src="https://user-images.githubusercontent.com/45767588/235967725-05a93747-3d2e-45ec-a2ff-7d5100a0d655.png">

**Comment by dmachi** [comment]
This is actually an error in the definition for this job that was exposed by a recent update.  Previously the system was ignoring the "binds" defined for a container (in config.json).  It is now actively using that information.  However, in this case, the job definition didn't have a bind defined for the "/job".  I have patched the service so that if there is no job bind found, it will automatically add one.  I re-ran this job in my account and it works.  Can you please re-run this and any others that you had fail?

**Comment by cckuhlman** [comment]
I will do now.  chris
________________________________

**Comment by cckuhlman** [comment]
All is working.  Great.  Thanks.

Will send a google drive link to you soon.

chris
________________________________
