### ISSUE TITLE
Confirm Input/Output file 

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#75]
@cckuhlman @Lucaslhm 

Murali has committed driver generation code along with the all inputs files, runXX : For 71 Snap method driver generation files.
And also committed the driver execution code for 10 snap method, below is the list:
1.	CntInDegNodes
2.	CntNonZNodes
3.	CntOutDegNodes
4.	CntSelfEdges
5.	CntUniqBiDirEdges
6.	CntUniqDirEdges
7.	CntUniqUndirEdges
8.	CommunityGirvanNewman
9.	ConvertGraph
10.	DelDegKNodes

As per our yesterday discussion, I have tried to add a list-of-primitive-type data type and able to generate the driver code.
Can you confirm whether the input and output file taken to run the code is correct or not? Please find the attachment of folder which contains:
1.	Infile66
2.	outIrForDriver66
3.	outIrSnapMethodOnly66
4.	inIrForDriver66.in
5.	inIrSnapMethodOnly66.in
6.	datatypes
7.	driver_auto_GetBfsEffDiam1_v01

Any pointer would be helpful for us.

[GetBfsEffDiam1.zip](https://github.com/NSSAC/CINES/files/4652054/GetBfsEffDiam1.zip)

Thanks,
Anju

**Comment by cckuhlman** [comment]
@anju-thute 

Hey Anju:

Sorry for my late reply.

Below are a list of things, some particular to infile66.inp, some more general.

1. This method has a "1" at the end of the name.  This should raise a flag in your head that something needs to be checked out (I never told you this before, so do not expect you to know).  For these methods, and **really this should be done for all methods**, you should go to here [https://snap.stanford.edu/snappy/doc/reference/GetBfsEffDiam.html?highlight=getbfseffdiam], the Snappy documentation, and see if you can search and find the name of the method that you are working on.  (Search facility on left.)   If you search for the textual name but cannot find the method (i.e., it does not exist), then we should not do this method---it is not in the official snappy documentation.  This should be documented here:  https://github.com/NSSAC/cines-snap-texts/tree/master/methods-to-implement

2. I went ahead and tried things anyhow, because it is an interesting case---the variables.  On line 267 of your driver code (file driver_auto_GetBfsEffDiam1_v01.py) has an indent problem.  "fhout.close()" is indented too far and therefore the code pukes.  When moving statement to the left, the code runs.

3.  I cannot check the template for this "output template" for a list-of-primitive-type in the datatypes.dat file because I think the file is not pushed to git (I do not see any file like this in the "outputs" template directory, and I do not see a variable of this name (or close to it) in the datatypes.dat file.  But I suspect the issue in (2) immediately above will be corrected if you change that particular statement in the template file for outputting the contents of a list with primitive entries.

4.  Also, if you can, please uses spaces to indent code lines, rather than tabs.

5.  I looked at your IRs and your driver code and I could see nothing wrong from visual inspection.  It all looked good.

6.  However, when I ran your driver, I got the issues specified above in (2).

7.  I am attaching a tarball of the contents of my local "GetBfsEffDiam1" directory under the "execute" directory that I used to test the method (under the driver constructor).  The method runs.  It produces results.  I do not know whether the results are correct because I do not understand the method.  It is non-standard, and may be why the method is not in the official list (i.e., that it is not searchable from the Snappy documentation).  Also, the input *.txt says that here should be 3 values output per line of results (i.e., that the list has 3 elements).  But this output only has two elements per line.  But this at least "semi" tests the datatypes.dat and this new output template (again, I am not looking at those files, only the resulting driver code).

9. The return type has a 3-line description.  You can either (1) modify the code so that it handles multiple description lines (the end of description will be a blank line), or (2) you can go into the infile66.inp file and move all three lines into one line.  (All the cases that I did the descriptions were on one line.)

10.  Was there particular issues, problems, questions, you had?

chris

**Comment by cckuhlman** [comment]
@Lucaslhm 
(Sorry, forgot to put you on with Anju.  I'm an issue-newbie)

**Comment by dmachi** [comment]
@cckuhlman For what its worth, I believe once you are mentioned on an issue,  you receive notifications for any comments on there..not just the comments that you are explicitly mentioned on.

**Comment by cckuhlman** [comment]
[cines.execute.files.run.66.tar.gz](https://github.com/NSSAC/CINES/files/4662511/cines.execute.files.run.66.tar.gz)

**Comment by cckuhlman** [comment]
One of my comments got cut off, or I deleted it.

The point is that the documentation states that there are three elements in the output list, but the code only generates two elements.  So there is an inconsistency, so we should not use this method.
