### ISSUE TITLE
Error while generating Driver code

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#82]
@cckuhlman @Lucaslhm 

While generating the driver code, I am getting error for the snap method: GetClustCfAll.
There is a parameter "DegToCCfV" which is used for output in float type. After generating the driver code getting an error in .py file that "DegToCCfV" variable in undefine.

When I tried to change the parameter "DegToCCfV" as the input type, then the .py file doesn't give an error. However when we execute this method then it gives an error.

I am attaching both the cases for your reference.

1- execution folder: [GetClustCfAll.zip](https://github.com/NSSAC/CINES/files/4690669/GetClustCfAll.zip)

2- python file with error and snap input file with "DegToCCfV" parameter as type input:
[pythonFile_with_error.txt](https://github.com/NSSAC/CINES/files/4690686/pythonFile_with_error.txt) [input_with error.txt](https://github.com/NSSAC/CINES/files/4690685/input_with.error.txt)

3- python file without error and snap input file with "DegToCCfV" parameter as type input:
[pythonFile_without_error.txt](https://github.com/NSSAC/CINES/files/4690713/pythonFile_without_error.txt) [input_without_error.txt](https://github.com/NSSAC/CINES/files/4690712/input_without_error.txt)

Any pointer would be helpful for us.

Thanks,
Anju

**Comment by cckuhlman** [comment]
@Lucaslhm 

There are a couple of issues here:

1. In the run.all file, the arguments are not correct.  There are two switches and the values for the two switches are missing.  All of this has been left out of the command line argument: 
--DegToCCfV  DegToCCfV   --SampleNodes  SampleNodes=-1  

So, the code will not run because the argparse is not parsing correctly.

2.  The argument DegToCCfV is a data structure of type TFltPrV, which is a vector of float pairs.  The problem is that the snap input file is wrong.
How to figure this out?
First, this is the site for the description of the method:  https://snap.stanford.edu/snappy/doc/reference/GetClustCfAll.html?highlight=getclustcfall
Second, this variable in question, DegToCCfV, has a type that is, **textually**:  a vector of pairs of floats.
This is bad---we want a particular datatype---not a textual description.
Third, this is a description of the type, but it is not the type.  So, what is the type?
Go to this page:
https://snap.stanford.edu/snappy/doc/tutorial/tutorial.html?highlight=graph%20types
You have to go through this page and find the text:  a vector of pairs of floats.
From this, we see a line:  TFltPrV, a vector of float pairs;
So, the type for variable DegToCCfV is TFltPrV.
This type needs to be put into the snap-provided text file, and remove "a vector of pairs of floats".
So, this should be noted in the summary *.md file as a change needed for the snap input text file.

This type is already in the datatypes.dat file.

So the following line must occur in the driver before the snap method is called:
DegToCCfV = snap.TFltPrV

So, there are two outputs:  the return type, and DegToCCfV.
Note thatt DegToCCfV is of signature type **output**.  So it is an output.
Thus, there must be two code segments to output data:  one for the return type and one for DegToCCfV.
Right now, there is only one, for the return type.

chris
