### ISSUE TITLE
GetLen2Paths : Getting error while executing driver code

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#97]
@cckuhlman @Lucaslhm 

For snap method **GetLen2Paths**, we are unable to execute driver code. 
Please refer to the attachment which contains all the required input.
[GetLen2Paths.zip](https://github.com/NSSAC/CINES/files/4711149/GetLen2Paths.zip)

1. The folder **constructing driver**: have all the driver constructing file and driver code .py file.
2. The folder **parsing**: have all the inputs required to parse the snap method.
3. The third folder **GetLen2Paths**"is to execute the driver code.

Thanks,
Anju

**Comment by cckuhlman** [comment]
Hey Anju:

Here are the files:
[Archive.zip](https://github.com/NSSAC/CINES/files/4711477/Archive.zip)

The two input graph files have been modified.  One directed and one undirected input file.
The run script has modified to point to the local version of the python main() method.
The output files have been generated and verified.  There are the output files and verified output files (*.valid).
The run.diff script has been updated.  Please note on this to print out the diff'ing operation being performed, so that if errors (differences) are printed to screen, then they can be associated with the correct file (this is done in 'run.diff').

chris

**Comment by cckuhlman** [comment]
Sorry, I omitted.  So, if you can run the code locally and get these results, for these inputs, then this code is working correctly.

**Comment by anju-thute** [comment]
Thanks, Chris!

Copied the provided .zip folder locally and tried to execute the driver, hence it is working correctly.
So we will commit the changes into the GitHub.

Thanks,
Anju
