### ISSUE TITLE
ConvertSubGraph : Getting error while executing driver code

### ISSUE THREAD

**Issue by anju-thute** [NSSAC/CINES#98]
@cckuhlman @Lucaslhm

For snap method **ConvertSubGraph**, we are unable to execute driver code.
Please refer to the attachment which contains all the required input.
[ConvertSubGraph.zip](https://github.com/NSSAC/CINES/files/4711169/ConvertSubGraph.zip)

The folder **constructing driver**: have all the driver constructing file and driver code .py file.
The folder **parsing**: have all the inputs required to parse the snap method.
The third folder **ConvertSubGraph** is to execute the driver code.

Thanks,
Anju

**Comment by cckuhlman** [comment]
This is a bizarre case and I describe now for when we come back to this.

There appears to be a problem with argparse, the python library.  It's hard to believe.  Essentially, there is a variable RenumberNodes.  If True, then the resulting (output) graph nodes are numbered 0 to n-1, where there are n nodes in the output subgraph.  If False, then the node IDs from the input graph are preserved.

The code works when this argument is False, and does not work when the argument is True.  We can live with the variable being False.
(We hardcode the value False, by writing False in the argument in the snap method call.)
This appears to be a problem with the Snap library method.
That is, when the argument is True, the failure comes in the invocation to snap method.

The second issue is that argparse changes the value of this argument on the command line.  That is, the value of bool variable RenumberNodes is changed from False to True inside of argparse, for no discernable reason.  Specifically, if RenumberNodes is set to False on the command line, then it is False in the sys.argv argument list.  But argparse then converts the variable to True.  We do not know why.  It is hard to believe that this is an argparse error, because it is such a normal case.  How can argparse be wrong?  But we even stripped the code down to bear-bones, and the code still gives this same error.

After finding the problem and trying cases to identify that RenumberNodes=False will work, I asked Lucas for help---because I figured for sure I was doing something stupid that made argparse set RenumberNodes = True---but we could not find an error in the Persistent code upon further checking.

So, right now, we have to leave as an error.
The most straightforward fix is to just make the argument False in the snap method call, and take it out of being a command line argument, but this creates problems from an auto-source code generation standpoint.

chris

**Comment by cckuhlman** [comment]
@anju-thute  (see above comment)

**Comment by murli1201** [comment]
Hi Chris,

@cckuhlman Considering the above comment, I manually deleted all the traces of Renumber Nodes from the driver code of ConvertSubGraph. Hence, on parsing the driver code, the run.all file ran successfully and the output files were created correctly.

So basically, now the input text file, IR's for driver & snap methods must consist the parameter "Renumber Nodes" but the driver code should not consist this parameter.

Is my understanding correct?

**Comment by cckuhlman** [comment]
Hey Murli:

I changed the textual input file containing the comments for the method ConvertSubGraph.  This is code #42.  I removed the last argument, Renumber nodes, as we spoke about last Tuesday.  I ran through building IRs, building driver code, and verifying code.  All is good, and the file that summarizes all methods has been updated.  See code number 42 in file here:  https://github.com/NSSAC/cines-snap-texts/blob/master/methods-to-implement/library-methods-to-implement.md

I think that this is now done.
